### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by apollo13**
I guess we could do a release with that and then work on the new webauthn stuff.

### CODE REVIEW

**Comment by apollo13** [comment]
Ups, yes I missed those -- thanks! Btw, I can't commit currently (on my phone) but you could port over the workflow changes from autopub to see early if the release stuff would work with the new autopub release :)

**Review by MarkusH — APPROVED** [review]

**Comment by justinmayer** [comment]
@apollo13: Good suggestion. I added a commit intended to port over what I think are the relevant CI configuration changes from the AutoPub repo. Would you have a look and let me know whether it looks right to you?

**Comment by apollo13** [comment]
You can remove the twine environment variables -- that is done by the upload action below automatically. But you need to copy the adjusted if statement down there as well

**Comment by justinmayer** [comment]
@apollo13: Done. Good catch on both counts. How does it look now?

**Comment by apollo13** [comment]
looks good, I mean we probably missed something but we won't know before we try? :D

**Review by justinmayer — APPROVED** [review]

**Comment by justinmayer** [comment]
Welp, I think perhaps we missed the part where the trusted publisher stuff gets set up in the non-test PyPI environment. 😓 https://github.com/justinmayer/kagi/actions/runs/5208770001/jobs/9397778566#step:7:20

**Comment by apollo13** [comment]
Oh yes, I thought you did that by now :)

**Comment by justinmayer** [comment]
No worries. I will take a look at the [relevant docs](https://docs.pypi.org/trusted-publishers/) as well as how it is configured in the test PyPI environment, in order to replicate that in the production PyPI environment.

I will also take the liberty of manually publishing the Kagi 0.4.0 release to PyPI, since all the other release steps have already been automatically completed.

**Comment by justinmayer** [comment]
[Kagi 0.4.0](https://pypi.org/project/kagi/0.4.0/) has been published to PyPI, and the trusted publisher configuration should be all set up in the production PyPI environment for future automated package publication. Thanks again to everyone who contributed to this release! 💫

**Pull request merged**
