### PR TITLE
Add support for trusted publishers

### PR DESCRIPTION
**Pull request by apollo13**
This is the second "minimal" attempt version. I refrained from to many cleanups, most of them can/should be done once https://github.com/autopub/autopub/pull/38 is merged.

I will test this in my branch against testpypi and get back to you with the results :)

### CODE REVIEW

**Comment by apollo13** [comment]
Successful run at https://github.com/apollo13/kagi/actions/runs/5162984001/jobs/9301054772

Required configuration on PyPI (replace apollo13 with justinmayer):
image

**Comment by apollo13** [comment]
Oh sorry, it fails on the follow up commit then, need to fix that :)

**Comment by apollo13** [comment]
@justinmayer Anything else you would like to see here so we can merge this?

**Comment by justinmayer** [comment]
> Required configuration on PyPI (replace apollo13 with justinmayer)

When and how exactly should this required configuration be performed?

**Comment by apollo13** [comment]
> When and how exactly should this required configuration be performed?

Anytime before we try to release a release using this new workflow. You just log into pypi, click "manage" for kagi and then add this under the "publishing" section.

**Review by justinmayer — APPROVED** [review]
Seems good to me. Nice work! 🌟

**Pull request merged**
